# Generated by Django 3.1.4 on 2020-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170829_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='state',
            field=models.IntegerField(choices=[(1, 'published'), (2, 'draft')], default=2, verbose_name='state'),
        ),
    ]
