# Generated by Django 3.1.4 on 2020-12-11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='body')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='create_time')),
                ('update_time', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='update_time')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='publish_time')),
                ('state', models.IntegerField(choices=[(1, 'published'), (2, 'draft')], default=2, verbose_name='state')),
                ('secret_key', models.CharField(blank=True, help_text='unique key for share url', max_length=8, unique=True, verbose_name='secret key')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'AboutPost',
                'verbose_name_plural': 'AboutPosts',
                'ordering': ('-publish_time',),
                'get_latest_by': 'publish_time',
            },
        ),
    ]
