version: '1'
services:
    db:
        image:mysql
        ports:
	-"3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: '546585847'
          MYSQL_USER: 'root'
          MYSQL_PASSWORD: '546585847'
          MYSQL_DATABASE: 'testmyweb'
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:5001
        volumes:
          - .:/code
        ports:
          - "5001:5001"
        depends_on:
          - db
